### ISSUE TITLE
Can't run the Navier-Stoke and Stoke equation

### ISSUE THREAD

**Issue by LeoXXVII** [gridap/Tutorials#96] opened 2021-07-17 15:40 UTC
When I am trying to run the notebook from the tutorial 8, 9 and 11 (Navier stoke, Stoke eq, and FSI respectively) but it appears the next error:

UndefVarError: _ConformingFESpace not defined

I read this same error in a discord server, but it was for an older version
But now, I just use the notebook from the dev tutorial and gridap v0.16.3, and this error occurs only when I use an order above 1. Using an order equal to 1 for velocity, the program didn't get any error (but yeah, is not part of the problem statement).

The code whe the problem appear is:

D = 2
order = 2
reffe = ReferenceFE(lagrangian,VectorValue{2,Float64},order)
V = TestFESpace(model,reffe;conformity=:H1,labels=labels,dirichlet_tags=["diri0","diri1"])

Is possible this is a typo?
Thank you

The rest of the error is: 
UndefVarError: _ConformingFESpace not defined
stacktrace:
 [1] FESpace(model::CartesianDiscreteModel{2, Float64, typeof(identity)}, cell_fe::Gridap.FESpaces.CellFE{FillArrays.Fill{Int64, 1, Tuple{Base.OneTo{Int64}}}}; labels::Gridap.Geometry.FaceLabeling, dirichlet_tags::Vector{String}, dirichlet_masks::Nothing, constraint::Nothing, vector_type::Type{Vector{Float64}})
   @ Gridap.FESpaces C:\Users\leona\.julia\packages\Gridap\293eQ\src\FESpaces\FESpaceFactories.jl:17
 [2] FESpace(model::CartesianDiscreteModel{2, Float64, typeof(identity)}, cell_reffe::FillArrays.Fill{Gridap.ReferenceFEs.GenericLagrangianRefFE{Gridap.ReferenceFEs.GradConformity, 2}, 1, Tuple{Base.OneTo{Int64}}}; conformity::Symbol, labels::Gridap.Geometry.FaceLabeling, dirichlet_tags::Vector{String}, dirichlet_masks::Nothing, constraint::Nothing, vector_type::Nothing)
   @ Gridap.FESpaces C:\Users\leona\.julia\packages\Gridap\293eQ\src\FESpaces\FESpaceFactories.jl:117
 [3] FESpace(model::CartesianDiscreteModel{2, Float64, typeof(identity)}, reffe::Tuple{Lagrangian, Tuple{DataType, Int64}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}; kwargs::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:conformity, :labels, :dirichlet_tags), Tuple{Symbol, Gridap.Geometry.FaceLabeling, Vector{String}}}})
   @ Gridap.FESpaces C:\Users\leona\.julia\packages\Gridap\293eQ\src\FESpaces\FESpaceFactories.jl:131
 [4] TestFESpace(::CartesianDiscreteModel{2, Float64, typeof(identity)}, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:conformity, :labels, :dirichlet_tags), Tuple{Symbol, Gridap.Geometry.FaceLabeling, Vector{String}}}})
   @ Gridap.FESpaces C:\Users\leona\.julia\packages\Gridap\293eQ\src\FESpaces\FESpaceFactories.jl:142
 [5] top-level scope
   @ In[5]:4
 [6] eval
   @ .\boot.jl:360 [inlined]
 [7] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1094

**Comment by amartinhuertas** [comment] 2021-07-19 01:10
Hi @LeoXXVII, 

I am not sure what is the cause of this problem.  

However, let me note that, in the latest commit of the Tutorials repo, all tests are passing in Github actions. This includes the tutorials you are mentioning. See the following log for more details:

https://github.com/gridap/Tutorials/runs/3086182508#step:6:1

Thus, it might be an environment issue in your computer and/or that the Jupyter notebooks you are trying to leverage are outdated (hypothesis). I would use the code corresponding the latest commit in the Tutorials repo.

Have you tried to execute the tutorials from the REPL directly from the shell or using an IDE, such as VSCode? (see https://github.com/gridap/Gridap.jl/wiki/Visual-Studio-Code-as-Julia-IDE)

**Comment by LeoXXVII** [comment] 2021-07-19 04:54
I tried too using VSCode using REPL directly, and appear the same error
And the code... i'm using the stable/dev version they are the same (v0.15.0). Is that the latest version, right?

**Comment by amartinhuertas** [comment] 2021-07-19 05:13
Are you cloning the Tutorials repo? If not, clone it, and use the code corresponding to the latest commit in the `master` branch. Release tag `v0.15.0` is not compatible with gridap 0.16, as stated here: https://github.com/gridap/Tutorials/blob/v0.15.0/Project.toml#L18

**Comment by LeoXXVII** [comment] 2021-07-19 05:32
Yeah, I clone it, and the same error.

note: the code _inc_navier_stokes.jl_ from the master version and the v0.15.0 are the same

**Comment by fverdugo** [comment] 2021-07-19 05:37
`Tutorials#master` is still pointing to Gridap v0.15. See https://github.com/gridap/Tutorials/blob/a3a03f82dc4112ab7b299971245294ab47518a2e/Project.toml#L22

I think we need to try if `Tutorials#gridap_v0.16` works with Gridap 0.16.3 and merge it to master eventually.

**Comment by fverdugo** [comment] 2021-07-19 05:39
So, the answer to this issue: the tutorials work for Gridap 0.15.x at this moment.

**Comment by amartinhuertas** [comment] 2021-07-19 05:56
>Tutorials#master is still pointing to Gridap v0.15.

Ok, I did only check Tutorials `v0.15.0`

>I think we need to try if Tutorials#gridap_v0.16 works with Gridap 0.16.3 and merge it to master eventually.

Yes, this is what we have to do. 

In any case, @LeoXXVII ... in the mean time/short term, can you checkout `Tutorials#gridap_v0.16` branch locally and check whether the tutorial you are interested in works? Otherwise, you should stick to Gridap 0.15.x, as @fverdugo mentions.

**Comment by amartinhuertas** [comment] 2021-07-19 05:57
> Yes, this is what we have to do.

I will do it soon.

**Comment by fverdugo** [comment] 2021-07-19 06:00
> I will do it soon.

Great! 

Note that in  Gridap v0.16.3 I have de-activated the MemoArray since this optimization is not reliable (it has caused some very subtle errors).

**Comment by LeoXXVII** [comment] 2021-07-19 06:12
Oh, oooooooooh
First, Thank you so much for your time and help, I was extremely nervous thinking "what I'm doing wrong? I'm still getting used to @_@"

> In any case, @LeoXXVII ... in the mean time/short term, can you checkout `Tutorials#gridap_v0.16` branch locally and check whether the tutorial you are interested in works? Otherwise, you should stick to Gridap 0.15.x, as @fverdugo mentions.

Yes, I'm interested in Navier-Stoke, Stoke eq, and FSI tutorials. 

Again, Thank you

**Comment by amartinhuertas** [comment] 2021-07-19 06:34
BTW ... @fverdugo ... do you remember why did you add the Manifest file in https://github.com/gridap/Tutorials/commit/49dc9c5b366c3af2aeb4fb23591b4cdc52c7c9b5?

**Comment by amartinhuertas** [comment] 2021-07-19 06:35
I guess because gridap v0.16 was not yet released at that time, right?

**Comment by fverdugo** [comment] 2021-07-19 09:30
Hi @LeoXXVII 

After PR #97, `Tutorials#master` points to Gridap 0.16.3.

Follow https://gridap.github.io/Tutorials/dev/#How-to-pull-the-latest-version-of-the-tutorials-1

Then, everything should work.

Closing for now.  Feel free to reopen if you have any problem.

**Closed by fverdugo** 2021-07-19 09:30 UTC
